### ISSUE TITLE
Ubuntu build

### ISSUE THREAD

**Issue by ninsbl** [rashadkm/webgrass#17]
Hi,

unfortunately webgrass does not build on Ubuntu 14.04 LTS, when following the README:

Scanning dependencies of target wgrass.wt
[  9%] Building CXX object CMakeFiles/wgrass.wt.dir/src/MainUI.cpp.o
In file included from /usr/include/Wt/WSignal:17:0,
                 from /usr/include/Wt/WWidget:14,
                 from /usr/include/Wt/WWebWidget:14,
                 from /usr/include/Wt/WInteractWidget:10,
                 from /usr/include/Wt/WContainerWidget:10,
                 from /usr/include/Wt/WAnchor:10,
                 from /usr/include/Wt/WPushButton:10,
                 from /data/src/webgrass/src/MainUI.h:10,
                 from /data/src/webgrass/src/MainUI.cpp:2:
/usr/include/boost/signal.hpp:17:4: warning: #warning "Boost.Signals is no longer being maintained and is now deprecated. Please switch to Boost.Signals2. To disable this warning message, define BOOST_SIGNALS_NO_DEPRECATION_WARNING." [-Wcpp]
 #  warning                  "Boost.Signals is no longer being maintained and is now deprecated. Please switch to Boost.Signals2. To disable this warning message, define BOOST_SIGNALS_NO_DEPRECATION_WARNING."
    ^
In file included from /data/src/webgrass/src/MainUI.h:24:0,
                 from /data/src/webgrass/src/MainUI.cpp:2:
/data/src/webgrass/src/Display.h:13:18: fatal error: Draw.h: No such file or directory
 #include "Draw.h"
                  ^
compilation terminated.
make[2]: **\* [CMakeFiles/wgrass.wt.dir/src/MainUI.cpp.o] Error 1
make[1]: **\* [CMakeFiles/wgrass.wt.dir/all] Error 2
make: **\* [all] Error 2

**Comment by mayank33** [comment]
Issue solved. Try now. Also check the updated readme.

**Comment by ninsbl** [comment]
Thanks! It builds now fine!
